load("@rules_python//python/uv:lock.bzl", "lock")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "pytest",
    srcs = ["pytest.bzl"],
    deps = [
        "@rules_python//python:py_test"
    ],
    visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

lock(
    name = "requirements",
    args = [
        "--all-extras",
        "--universal",
    ],
    srcs = ["//:pyproject.toml"],
    out = "requirements.txt",
)

# dist files

exports_files(
    [
        "README.md",
        "CHANGELOG.md",
        "CONTRIBUTING.md",
        "LICENSE",
    ],
    visibility = ["//:__subpackages__"],
)
