load("@rules_python//python/uv:lock.bzl", "lock")

licenses(["notice"])  # Apache 2.0

lock(
    name = "requirements",
    args = [
        "--all-extras",
        "--universal",
    ],
    srcs = ["//:pyproject.toml"],
    out = "requirements.txt",
)

# dist files

exports_files(
    [
        "README.md",
        "CHANGELOG.md",
        "CONTRIBUTING.md",
        "LICENSE",
    ],
    visibility = ["//:__subpackages__"],
)
