load("@rules_python//python:py_test.bzl", "py_test")
load("@rules_python//python:py_library.bzl", "py_library")

py_library(
    name = "test_example",
    srcs = ["test_example.py"],
    testonly = True,
)

py_test(
    name = "test_simple",
    main_module = "pytest_bazel",
    deps = [
        "@pypi//pytest_bazel",
        ":test_example",
    ],
    testonly = True,
)
