---
name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    environment:
      name: release
      url: https://pypi.org/p/pytest-bazel
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dist folder
        run: |
          bazel run //pkg:prepare

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: dist/*.whl
